#应用端口
server:
  port: 8091

#Dubbo
dubbo:
  application:
    name: user
    qos-port: 22223
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://localhost:2181

#连接池
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useSSL=false
    username: root
    password: 2669019760

#MyBatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.stedu.mall.common.bean

white-list:
  rules:
    - regPath: ^/user/captcha*
      method: GET
    - regPath: ^/user/login
      method: POST
