#应用端口
server:
  port: 8093

#Dubbo
dubbo:
  application:
    name: order
    qos-port: 22222
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://localhost:2181

#连接池
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useSSL=false
    username: root
    password: 2669019760

#MyBatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.stedu.mall.common.bean

stedu:
  picDir: D:/pic/
