#应用端口
server:
  port: 8092

#连接池
spring:
  application:
    name: admin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useSSL=false
    username: root
    password: 2669019760
  redis:
    host: localhost
    port: 6379
    password: 123456

#seata
seata:
  registry:
    type: zk
    zk:
      server-addr: 127.0.0.1:2181
      session-timeout: 6000
      connect-timeout: 2000
      username:
      password:
  tx-service-group: mall
  service:
    # 事务分组与集群映射关系
    vgroup-mapping:
      mall: seata


#MyBatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.stedu.mall.common.bean

white-list:
  rules:
    - regPath: ^/admin/captcha*
      method: GET
    - regPath: ^/admin/login
      method: POST


